# Generated by Django 3.1 on 2023-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres y Apellidos:')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI:')),
                ('gender', models.CharField(choices=[['M', 'Mujer'], ['H', 'Hombre'], ['O', 'Otros']], max_length=1, verbose_name='Género:')),
                ('number', models.CharField(max_length=9, verbose_name='Número de celular:')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico:')),
                ('age', models.IntegerField(verbose_name='Edad:')),
                ('moto_choice', models.IntegerField(choices=[[0, 'DEPORTIVA'], [1, 'NAKED'], [2, 'SCOOTER'], [3, 'DOBLE PROPÓSITO - TODO TERRENO'], [4, 'CAFÉ RACER'], [5, 'CRUISER - CHOPPER'], [6, 'TOURING - VIAJERAS'], [7, 'ENDURO - CROSS']], verbose_name='¿Qué tipo de motos te gustan?')),
                ('moto', models.BooleanField(choices=[[True, 'Sí'], [False, 'No, soy motero sin moto.']], verbose_name='¿Tienes moto?')),
                ('subscription', models.BooleanField(default=False, verbose_name='QUIERO SER PARTE DE LA FAMILIA MOTERA DEL LOCO IORI.')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
        ),
    ]
